name: Update README2

on:
schedule:
  - cron: "* */12 * * *"
  workflow_dispatch:

  jobs:
    build:
        runs-on: ubuntu-latest
        name: update profile readme

        steps:
          - uses: actions/checkout@v2.3.4

          - uses: readme-Workflows/recent-activity@v2.4.1
            env:
              GITHUB_TOKEN: ${( secrests.GITHUB_TOKEN )}
  
